notification_server:
  PORT: ":50052"
  GRACE_PERIOD: "3s"

http:
  METRICS_LISTEN_ADDR: ":10904"

smtp_client:
  HOST: "mailhog"                 
  PORT: "1025"
  USER: "..."
  PASS: "..."
  FROM: "no-reply@match.com"

logging:
  LEVEL: "info"
  FORMAT: "json"
  DEBUG_NAME: ""

flagd:
  flags_path: "./flags.flagd.json"