notification_server:
  PORT: ":50052"
  GRACE_PERIOD: "3s"

http:
  METRICS_LISTEN_ADDR: ":10904"

smtp_client:
  HOST: "127.0.0.1"
  PORT: "1025"
  USER: "..."
  PASS: "..."
  FROM: "no-reply@match.com"

logging:
  LEVEL: "debug"
  FORMAT: "json"
  DEBUG_NAME: ""

flagd:
  flags_path: "./config/flags.flagd.json"

code_generator:
  expires_at: "10m"
  count_digits: 6
  max_attempts: 5