user_service_client:
  GRPC_ADDR: "user:50051"         # в докере идём по имени сервиса

notification_service_client:
  GRPC_ADDR: "notification:50052"

http:
  LISTEN_ADDR: ":8000"
  METRICS_LISTEN_ADDR: ":10902"   # подровняй healthcheck/Prometheus

smtp_client:
  HOST: "mailhog"                 # или host.docker.internal
  PORT: "1025"
  USER: "..."
  PASS: "..."
  FROM: "no-reply@match.com"

logging:
  LEVEL: "info"
  FORMAT: "json"
  DEBUG_NAME: ""

front_end:
  FRONT_END_PATH: "/app/webwasm"

kafka:
  producer:
    brokers: ["kafka:9092"]
    client_id: "auth-svc-consumer"
    flush_timeout_ms : 10000

  consumer:
    brokers: ["kafka:9092"]
    client_id: "auth-svc-consumer"
    broker_address_family: "v4"
    group_id: "notification"
    session_timeout_ms: 6000
    auto_offset_reset: "earliest"
    max_poll_interval_ms: 600000

flagd:
  flags_path: "./flags.flagd.json"