user_service_server:
  PORT: ":50051"
  GRACE_PERIOD: "3s"

http:
  METRICS_LISTEN_ADDR: ":10903"

logging:
  LEVEL: "info"
  FORMAT: "json"
  DEBUG_NAME: ""

flagd:
  flags_path: "./flags.flagd.json"